# Generated by Django 4.1.3 on 2022-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='DNI'),
        ),
    ]
