# Generated by Django 4.1.3 on 2022-11-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
    ]
