# Generated by Django 4.1.3 on 2022-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(help_text='Matricula', max_length=100)),
                ('marca', models.CharField(help_text='Marca', max_length=100)),
                ('modelos', models.CharField(help_text='Modelo', max_length=100)),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
            },
        ),
    ]
